// <auto-generated />
namespace BecaDotNet.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NewAtributtesUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewAtributtesUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201808301359406_NewAtributtesUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
